config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :listings do
    resources :rentals, only: [:create]
  end

  resources :rentals, only: [:show] do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :users, only: [:show]

  get '/dashboard', to: 'dashboard#overview'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Temporary routes to view components, delete later:
  get '/list-items-preview', to: 'pages#list_items_preview'
  get '/reviews_component_preview', to: 'pages#reviews_component_preview'
  get '/borrow_lend_item_preview', to: 'pages#borrow_lend_item_preview'
  get '/carousel_test_page', to: 'pages#carousel_test_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :title, presence: true
end

app/models/listing.rb
class Listing < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  
  belongs_to :game
  belongs_to :user
  has_many :rentals
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model

  CONSOLES = ["PS4", "Xbox One", "Nintendo Switch", "PC"]
  validates :platform, inclusion: { in: CONSOLES }

  pg_search_scope :global_search, against: [:platform],
                                  associated_against: { game: [:title] },
                                  using: { tsearch: { prefix: true } }

  def unavailable_dates
    rentals.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :listing
  belongs_to :user, foreign_key: "customer_id"
  before_save :set_rental_price
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  def duration
    start_date = self.start_date
    end_date = self.end_date
    (end_date - start_date + 1).to_i
  end

  def set_rental_price
    total_price = self.duration * self.listing.price
    self.rental_fee = total_price
  end

  private
  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: { in: 1..5 }
  belongs_to :rental
end

app/models/user.rb
class User < ApplicationRecord
  # validates :username, presence: true

  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings
  has_many :rentals, foreign_key: "customer_id", class_name: "Rental"

  has_many :reviews, through: :rentals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?
  include Pundit

after_action :verify_authorized, except: %i[index overview], unless: :skip_pundit?

private

def skip_pundit?
  devise_controller? ||
    params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
end

    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :photo])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def overview
    @user = current_user
    @lends = Rental.where(listing_id: @user.listings.pluck(:id))
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  before_action :set_listing, only: %i[show edit update destroy]
  require 'date'

  def show
    @rental = Rental.new
    @today = Date.today
    authorize @listing
  end

  def index
    @listings = Listing.all
    @listing_map = Listing.geocoded
    @markers = @listing_map.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { listing: listing })
      }
    end
    if params[:search]
      if params[:search][:name].present?
        @search_query = params[:search][:name]
        @listings = @listings.global_search(@search_query)
        @title = "Results for \"#{@search_query}\""
      end
      if params[:search][:platform].present?
        @listings = @listings.where(platform: params[:search][:platform])
      end
    end
  end

  def new
    @listing = Listing.new
    authorize @listing
  end

  def create
    @listing = Listing.new(listing_params)
    authorize @listing
    @listing.user = current_user
    if @listing.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    authorize @listing
  end

  def update
    authorize @listing
    @listing.update(listing_params)
    if @listing.save
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    authorize @listing
    @listing.destroy
    redirect_to dashboard_path
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def listing_params
    params.require(:listing).permit(:price, :location, :game_id, :platform, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @all_listings = Listing.all
    @listings = Listing.order('RANDOM()').limit(15)
  end

  # Temporary routes for showing CSS components. Delete later, along with the associated views
  def list_items_preview
  end

  def reviews_component_preview
  end

  def borrow_lend_item_preview
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def show
    @rental = Rental.find(params[:id])
    authorize @rental
    @review = Review.new()
    #@rental_fee = @rental.rental_fee
  end

  def create
    @rental = Rental.new(rental_params)
    authorize @rental
    @rental.user = current_user
    @listing = Listing.find(params[:listing_id])
    @rental.listing = @listing
    if @rental.save
      redirect_to rental_path(@rental)
    else
      render :new
    end
  end


  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def create
  @review = Review.new(review_params)
  @rental = Rental.find(params[:rental_id])
  @review.rental = @rental
  authorize @review
  if @review.save
    redirect_to rental_path(@rental)
  else
    render :create
  end
end

def edit
  @review = Review.find(params[:id])
  authorize @review
end

def update
  @review = Review.find(params[:id])
  authorize @review
  @review.update(reviews_params)
  redirect_to review_path
end

def destroy
  @review = Review.find(params[:id])
  authorize @review
  @review.destroy
  redirect_to review_path
end

private

def review_params
  params.require(:review).permit(:rating, :review_content)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # user and user_profile need different instance variables here for
    # authentication  and data display purposes
    @user_profile = User.find(params[:id])
    @user = current_user
    @listings_id = @user_profile.listings.pluck(:id)
    @rentals_id = Rental.where(listing_id: @listings_id[0]).pluck(:id)
    @reviews = Review.where(rental_id: @rentals_id)
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/overview.html.erb
<div class="container">
  <div class="row my-5 justify-content-between">
    <div>
      <h1>Welcome, <%= @user.first_name %></h1>
      <p><strong class="orange">Your username:</strong> <%= @user.username %></p>
    </div>
    <div style="padding-top: 14px">
      <%= link_to "View profile", user_path(current_user), class: "primary_button mx-2" %>
      <%= link_to "Edit profile", edit_user_registration_path, class: "primary_button" %>
    </div>
  </div>
  <div class="row my-5 py-4 flex-column">
    <h2>Your listings:</h2>
      <% if @user.listings.empty? %>
        <p>You haven't listed any games yet.</p>
      <% else %>
        <div class="listing-list">
          <% @user.listings.each do |listing| %>
            <div class="listing-item">
              <div class="listing-item-image">
                <% case listing.platform %>
                  <% when "PC" %>
                    <%= image_tag 'pc-temp-tag.png', class: "console-tag" %>
                  <% when "PS4" %>
                    <%= image_tag 'ps4-temp-tag.png', class: "console-tag" %>
                  <% when "Xbox One" %>
                    <%= image_tag 'xboxone-temp-tag.png', class: "console-tag" %>
                  <% when "Nintendo Switch" %>
                    <%= image_tag 'switch-temp-tag.png', class: "console-tag" %>
                <% end %>
                <img src=<%= listing.game.image %> class="rounded">
              </div>
              <div class="listing-item-text">
                  <h3 class="orange"><%= link_to listing.game.title, listing_path(listing) %></h3>
                  <div class="listing-info"><p class='text_small'><strong>Platform</strong> <%= listing.platform %> &nbsp;&nbsp;|&nbsp;&nbsp; <strong>Genre </strong><%= listing.game.genre %></p></div>
              </div>
              <div class="listing-item-buttons">
                <div><h2>£<%= listing.price %></h2><p class="text_small">per day</p></div>
                <ul class="list-inline">
                  <li class="list-inline-item">
                    <%= link_to edit_listing_path(listing) do %>
                      <i class="fas fa-edit"></i>
                    <% end %>
                  </li>
                  <li class="list-inline-item">
                    <%= link_to listing_path(listing), method: :delete, data: { confirm: 'Are you sure you want to remove this listing?' } do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
  <div class="row my-5 py-4 flex-column">
    <h2>Your lends:</h2>
      <% if @lends.empty? %>
        <p>You haven't lent any games out yet.</p>
      <% else %>
        <div class="listing-list">
          <% @lends.each do |lend| %>
            <div class="booking-item">
              <div class="booking-item-image">
                <% case rental.listing.platform %>
                  <% when "PC" %>
                    <%= image_tag 'pc-temp-tag.png', class: "console-tag" %>
                  <% when "PS4" %>
                    <%= image_tag 'ps4-temp-tag.png', class: "console-tag" %>
                  <% when "Xbox One" %>
                    <%= image_tag 'xboxone-temp-tag.png', class: "console-tag" %>
                  <% when "Nintendo Switch" %>
                    <%= image_tag 'switch-temp-tag.png', class: "console-tag" %>
                <% end %>
                <%= image_tag lend.listing.game.image, class: "booking-item-game-image rounded" %>
              </div>
              <div class="booking-item-text">
                <h4><%= link_to lend.listing.game.title, rental_path(lend) %></h4>
                <div class="booking-info"><p class='text_small'><strong>Start Date</strong> <%= lend.start_date %> &nbsp;&nbsp;|&nbsp;&nbsp; <strong>End Date</strong> <%= lend.end_date %> &nbsp;&nbsp;|&nbsp;&nbsp; <strong>Length of rental&nbsp;</strong> <%= lend.duration %> days</p></div>
                <p><strong>Lent to</strong> <%= link_to lend.user.username, user_path(lend.user) %></p>
                <p><strong>Total earnings</strong> $<%= lend.rental_fee %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
  <div class="row my-5 py-4 flex-column">
    <h2>Your borrows:</h2>
    <% if @user.rentals.empty? %>
      <p>You haven't borrowed any games yet.</p>
    <% else %>
      <div class="listing-list">
        <% @user.rentals.each do |rental| %>
          <div class="booking-item">
            <div class="booking-item-image">
              <% case rental.listing.platform %>
                <% when "PC" %>
                  <%= image_tag 'pc-temp-tag.png', class: "console-tag" %>
                <% when "PS4" %>
                  <%= image_tag 'ps4-temp-tag.png', class: "console-tag" %>
                <% when "Xbox One" %>
                  <%= image_tag 'xboxone-temp-tag.png', class: "console-tag" %>
                <% when "Nintendo Switch" %>
                  <%= image_tag 'switch-temp-tag.png', class: "console-tag" %>
              <% end %>
              <%= image_tag rental.listing.game.image, class: "booking-item-game-image rounded" %>
            </div>
            <div class="booking-item-text">
              <h4 class="orange"><%= link_to rental.listing.game.title, rental_path(rental) %></h4>
              <div class="booking-info"><p class='text_small'><strong>Start Date</strong> <%= rental.start_date %> &nbsp;&nbsp;|&nbsp;&nbsp; <strong>End Date</strong> <%= rental.end_date %> &nbsp;&nbsp;|&nbsp;&nbsp; <strong>Length of rental&nbsp;</strong> <%= rental.duration %> days</p></div>
              <p><strong>Borrowed from</strong> <%= link_to rental.listing.user.username, user_path(rental.listing.user) %></p>
              <p><strong>Total price</strong> $<%= rental.rental_fee %></p>
            </div>
          </div>        
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Airp2p - Lend, borrow, share your games</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <div class="content">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/listings/_info_window.html.erb
<h2><%= link_to listing.game.title ,listing_path(listing) %></h2>
<p><%= listing.location %></p>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/index.html.erb
<div class="content-wrapper">
  <div class="listing-list">
    <h1>All Listings</h1>

    <% @listings.each do |listing| %>
      <%= link_to listing_path(listing) do %>
        <div class="listing-item">
          <div class="listing-item-image">
            <% case listing.platform %>
            <% when "PC" %>
              <%= image_tag 'pc-temp-tag.png', class: "console-tag" %>
            <% when "PS4" %>
              <%= image_tag 'ps4-temp-tag.png', class: "console-tag" %>
            <% when "Xbox One" %>
              <%= image_tag 'xboxone-temp-tag.png', class: "console-tag" %>
            <% when "Nintendo Switch" %>
              <%= image_tag 'switch-temp-tag.png', class: "console-tag" %>
            <% end %>
            <img src=<%= listing.game.image %> class="rounded">
          </div>
          <div class="listing-item-text">
            <h3 class="orange"><%=listing.game.title %></h3>
            <div class="listing-info"><p class='text_small'><strong>Platform</strong> <%= listing.platform %> &nbsp;&nbsp;|&nbsp;&nbsp; <strong>Genre</strong> <%= listing.game.genre %></p></div>
            <p><strong>Available from</strong> <%= listing.user.username %></p>
            <p><strong>Distance</strong>
              <% user_location = [52.37819, 4.89982] %>
              <% array_for_listing = [listing.latitude, listing.longitude] %>
              <%= Geocoder::Calculations.distance_between(user_location, array_for_listing).round(1) %> km away
            </p>
          </div>
          <div class="listing-item-buttons">
            <div><h2>$<%= listing.price %></h2><p class="text_small">per day</p></div>
            <ul class="list-inline hidden">
              <li class="list-inline-item"><i class="fa fa-heart"></i></li>
              <li class="list-inline-item"><i class="fa fa-share"></i></li>
              <li class="list-inline-item"><i class="fa fa-star"></i></li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id = "map" class ="mapbox-map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

</div>

app/views/listings/show.html.erb
<div class="container my-5">
  <div class="row no-left-mg">
    <div class="col-md-4 col-lg-3 imagesize listing-item2 no-left-pd selected-card py-0">
      <% case @listing.platform %>
      <% when "PC" %>
        <%= image_tag 'pc-temp-tag.png', class: "console-tag2" %>
      <% when "PS4" %>
        <%= image_tag 'ps4-temp-tag.png', class: "console-tag2" %>
      <% when "Xbox One" %>
        <%= image_tag 'xboxone-temp-tag.png', class: "console-tag2" %>
      <% when "Nintendo Switch" %>
        <%= image_tag 'switch-temp-tag.png', class: "console-tag2" %>
      <% end %>
      <% if @listing.photo.present? %>
        <%= cl_image_tag  @listing.photo, class: "game_image fit-image" %>
      <% else %>
        <img class="game_image fit-image" src= <%= @listing.game.image %> alt="">
      <% end %>
    </div>

    <div class="col-md-4 col-lg-6 selected-card pt-2 position-relative mh-100">
      <h2><%= @listing.game.title %></h2>
      <h5 >Description</h5>
      <p class = "mb-2"><%= @listing.game.title %><%= @listing.game.description.truncate(150) %></p>
      <h5>Platform</h5>
      <p class = "mb-2"><%= @listing.platform %>  </p>
      <h5>Lender</h5>
      <p class = "mb-2"><%= link_to @listing.user.username, user_path(@listing.user) %></p>
      <h5>Location</h5>
      <p class = "mb-2" ><%= @listing.location %></p>
      <br>
      <h3 class = "bottom0">Price per day:  $<span id="price"><%= @listing.price %></span></h3>
    </div>

      <% if user_signed_in? %>
        <% if current_user.id != @listing.user_id  %>
        <div class="col-md-4 col-lg-3 bookcard">
          <div class="form-group py-2">
            <h3>Book your game</h3>
            <div id='listing-booking-dates' data-unavailable="<%= @listing.unavailable_dates.to_json %>">
              <%= simple_form_for [@listing, @rental] do |f| %>
                <% @rental.errors.full_messages.each do |message| %>
                  <%= message %>
                <% end %>
                <div class = "date-sbs">
                  <%= f.input :start_date, as: :string, type: :text, input_html: {value: @today} %>
                  <%= f.input :end_date, as: :string, type: :text, wrapper_html: {class: 'ml-2'} %>
                </div>
                <h4>Total price:</h4><h4 id="total_price"></h4>
                <%= f.submit "Book", class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="col-md-4 d-flex col-lg-3 bookcard position-relative">
            <div class = "mx-auto d-flex justify-content-around align-items-center top-right">
            <%= link_to edit_listing_path(@listing) do %>
                      <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to listing_path(@listing), method: :delete, data: { confirm: 'Are you sure you want to remove this listing?' } do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
          </div>
        <% end %>
      <% else %>
          <div class="col-md-4 col-lg-3 bookcard">
          <h3>Sign in to book</h3>
      <% end %>
    </div>
  </div>
</div>





<%#= javascript_pack_tag 'listing_show' %>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/pages/home.html.erb
<div class="row home-section">
  <div class="col-12">
    <div class="banner">
      <h1>Borrow, lend, share.</h1>
      <p>A place for gamers to play more with less.</p>
      <div class="home-search">
        <%= simple_form_for :search, url: listings_path, method: "GET", html: { class: 'form-inline home-search' } do |f| %>
          <%= f.input :name, label: false, placeholder: "search for games", input_html: {value: "", class: "home-search-bar ui-autocomplete-input"} %>
          <%= f.input :platform, label: false, prompt: "Any console", collection: Listing::CONSOLES, input_html: {class: "home-search-platform"} %>
          <%= f.submit "Search", class: "btn btn-primary search-submit mx-auto" %>
        <% end %>
      </div>
    </div>

    <div class="home_carousel">
      <div class="carousel__inner">
        <% @listings.each do |listing| %>
            <div class="tile">
              <%= link_to listing_path(listing) do %>
              <div class="tile__media">
                <img class="tile__img" src="<%= listing.game.image %>" alt=""  />
              </div>
              <div class="tile__details">
                <div class="tile__title">
                  <h5><%= listing.game.title %></h5>
                  <p class="orange" id="lend-from"><strong>Lend from</strong></p>
                  <p><%= listing.user.username %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="home-section home-section-2">
    <h2>How it works</h2>
    <div class="card-group">
      <div class="card text-center home-card">
        <i class="fas fa-list-ol orange"></i>
        <div class="card-body">
          <h5 class="card-title">List your games for others</h5>
          <p class="card-text">Advertise your game collection so others can borrow your games and you can get some extra cash back.</p>
        </div>
      </div>
      <div class="card text-center home-card">
        <i class="fas fa-retweet orange"></i>
        <div class="card-body">
          <h5 class="card-title">Borrow games from other members</h5>
          <p class="card-text">Look through the communities catalog to find titles you want to play, for less.</p>
        </div>
      </div>
      <div class="card text-center home-card">
        <i class="fas fa-gamepad orange"></i>
        <div class="card-body">
          <h5 class="card-title">Play more for less!</h5>
          <p class="card-text">Start playing more games for less! Join a growing community of sharing gamers.</p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/rentals/create.html.erb
<h1>Rentals#create</h1>
<p>Find me in app/views/rentals/create.html.erb</p>

app/views/rentals/create.js.erb
const total_price_display = document.querySelector('#total_price');
total_price_display.innerText = '<%=@rental.rental_fee %>'

app/views/rentals/show.html.erb
<div class="container">
  <div class="listing-list-selected listing-list-gray container">
    <h1 class = gray>Rental Details</h1>
    <div class="listing-item-selected bottom-margin-50">
      <div class="listing-item-image">
        <% case @rental.listing.platform %>
        <% when "PC" %>
          <%= image_tag 'pc-temp-tag.png', class: "console-tag" %>
        <% when "PS4" %>
          <%= image_tag 'ps4-temp-tag.png', class: "console-tag" %>
        <% when "Xbox One" %>
          <%= image_tag 'xboxone-temp-tag.png', class: "console-tag" %>
        <% when "Nintendo Switch" %>
          <%= image_tag 'switch-temp-tag.png', class: "console-tag" %>
        <% end %>
        <img src=<%= @rental.listing.game.image %> class="rounded">
      </div>
      <div class="listing-item-text">
        <h3 class="orange"><%=@rental.listing.game.title %></h3>
        <div class="listing-info"><p class='text_small'><strong>Platform</strong> <%= @rental.listing.platform %> &nbsp;&nbsp;|&nbsp;&nbsp; <strong>Genre</strong> Third Person</p></div>
        <p><strong>Rental from <%= @rental.start_date %> until <%= @rental.end_date %></strong></p>
        <p><strong>Borrowed by</strong> <%= link_to @rental.user.username, user_path(@rental.user), class: "orange" %></p>
        <p><strong>Lent by</strong> <%= link_to @rental.listing.user.username, user_path(@rental.listing.user), class: "orange" %></p>
        <p></p>
      </div>
      <div class="listing-item-buttons">
        <div><h2 class="orange">$<%= @rental.rental_fee %></h2><p class="text_small">Total rental fee</p></div>
        <ul class="list-inline hidden">
          <li class="list-inline-item"><i class="fa fa-heart"></i></li>
          <li class="list-inline-item"><i class="fa fa-share"></i></li>
          <li class="list-inline-item"><i class="fa fa-star"></i></li>
        </ul>
      </div>
    </div>
    <% if current_user != @rental.listing.user %>
      <div class="form-group p-5 rating_card gray">
        <h3>Review the rental experience with <%= @rental.listing.user.username %></h3>
        <%= simple_form_for [@rental, @review] do |f|  %>
          <% @review.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
          <%= f.input :rating, collection: [1,2,3,4,5],as: :radio_buttons, wrapper: :vertical_collection_inline %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-airconsole">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "airp2p-logo.svg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsupportedcontent" aria-controls="navbarsupportedcontent" aria-expanded="false" aria-label="toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= link_to "List your games", new_listing_path, class: "primary_button"  %>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link nav-link-custom" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.blank? %>
            <%= image_tag "default_user_icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link nav-link-custom" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link nav-link-custom" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>